#!/usr/bin/env bash
# Transfer file to server
file=$1
ip=$2
username=$3
p_key=$4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$p_key" "$file" "$username@$ip":~
fi
