#!/usr/bin/env bash
# Install nginx web server on a remote server
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
