#!/usr/bin/env bash
# Install nginx web server on a remote server
apt-get -y upgrade
apt-get -y install nginx
chown -R $USER:$USER /var/www/html/index.nginx-debian.html
ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
