#!/usr/bin/env bash
# Install nginx web server on a remote server
apt-get upgrade
apt-get -y install nginx
chown -R ubuntu /var/www
ufw --force enable
echo "Hello World!" > /var/www/html/index.html
service nginx start
