#!/usr/bin/env bash
# Configure NGINX web server then
# redirect /redirect_me to another location
redirect="#n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
file="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a $redirect" "$file"
service nginx restart
