#!/usr/bin/env bash
# Configure NGINX web server then
# redirect /redirect_me to another location
# create custome 404 error location
redirect="#n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
file="/etc/nginx/sites-available/default"
error="#n\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
error_message="Ceci n'est pas une page"
header="#n\n\tadd_header X-Served-By \$HOSTNAME;"
apt-get -y update
apt-get -y install nginx
chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a $header" "$file"
sed -i "/server_name _;/a $redirect" "$file"
echo "$error_message" > /usr/share/nginx/html/custom_404.html
sed -i "/server_name _;/a $error" "$file"
service nginx restart
