#!/usr/bin/env bash
# install and configure HAproxy
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get -y install haproxy=2.6.\*
chown -R "$USER" /etc/haproxy/haproxy.cfg
chown -R "$USER" /etc/default/haproxy
printf %s "
backend webservers
       balance roundrobin
       server 121016-web-01 54.173.86.57:80 check
       server 121016-web-02 100.26.227.44:80 check

frontend http
       bind *:80
       mode http
       default_backend webservers
" >> /etc/haproxy/haproxy.cfg
# Make sure that HAproxy can be managed via an init script
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
