#!/usr/bin/env bash
# dump all databases and compress to a .tar.gz
mysqldump -uroot --password="$1" --all-databases > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
filename="$day-$month-$year.tar.gz"
tar -cvzf "$filename" backup.sql
