#!/usr/bin/env bash
# handle errors
#rm /etc/nginx/sites-available/default
#ln -s /etc/nginx/sites-available/default default
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
#service nginx restart
pgrep nginx -o > /run/nginx.pid
nginx -s reload
echo '' > /run/nginx.pid
